In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as si
import yfinance as yf
import os

In [2]:
TSLA = yf.download("TSLA", start="2020-12-04", end="2021-12-04")

[*********************100%***********************]  1 of 1 completed


In [3]:
S = TSLA['Adj Close'][-1]
print('The spot price is $', round(S,2), '.')

The spot price is $ 1014.97 .


In [4]:
log_return = np.log(TSLA['Adj Close'] / TSLA['Adj Close'].shift(1))
vol_h = np.sqrt(252) * log_return.std()
print('The annualised volatility is', round(vol_h*100,2), '%')

The annualised volatility is 54.56 %


In [5]:
def newton_vol_call(S, K, T, C, r):
    
    #S: spot price
    #K: strike price
    #T: time to maturity
    #C: Call value
    #r: risk free rate
    #sigma: volatility of underlying asset
   
    MAX_ITERATIONS = 1000
    tolerance = 0.000001
    
    sigma = 0.25
    
    for i in range(0, MAX_ITERATIONS):
        d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
        d2 = (np.log(S / K) + (r - 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
        price = S * si.norm.cdf(d1, 0.0, 1.0) - K * np.exp(-r * T) * si.norm.cdf(d2, 0.0, 1.0)
        vega = S * np.sqrt(T) * si.norm.pdf(d1, 0.0, 1.0)

        diff = C - price

        if (abs(diff) < tolerance):
            return sigma
        else: 
            sigma = sigma + diff/vega
        
        # print(i,sigma,diff)
        
    return sigma

In [7]:
TESLA = yf.Ticker("TSLA")
opt = TESLA.option_chain('2022-01-21')
opt.calls


contractSymbol       lastTradeDate  strike  lastPrice      bid  \
0    TSLA220121C00001000 2022-01-07 15:15:43     1.0    1051.45  1077.95   
1    TSLA220121C00002000 2022-01-07 15:42:09     2.0    1036.60  1074.85   
2    TSLA220121C00003000 2022-01-06 15:11:35     3.0    1018.85  1074.85   
3    TSLA220121C00004000 2022-01-06 15:41:21     4.0    1046.95  1073.85   
4    TSLA220121C00005000 2022-01-11 20:23:16     5.0    1052.30  1073.45   
..                   ...                 ...     ...        ...      ...   
519  TSLA220121C03700000 2020-08-26 17:26:15  3700.0     352.70   398.00   
520  TSLA220121C03800000 2020-08-27 19:59:56  3800.0     397.00   383.50   
521  TSLA220121C04000000 2020-08-28 17:33:09  4000.0     367.85   357.50   
522  TSLA220121C04100000 2020-08-27 14:09:15  4100.0     323.85   345.50   
523  TSLA220121C04200000 2020-08-28 19:49:31  4200.0     343.00   332.00   

         ask     change  percentChange  volume  openInterest  \
0    1092.35   0.000000        0.00000     1.0           107   
1    1091.25   0.000000        0.00000     1.0             2   
2    1086.35   0.000000        0.00000     3.0             8   
3    1085.60   0.000000        0.00000     5.0             6   
4    1088.45   0.000000        0.00000    34.0           617   
..       ...        ...            ...     ...           ...   
519   417.50   0.000000        0.00000     NaN             1   
520   403.00   0.000000        0.00000     NaN            17   
521   377.00  22.850006        6.62319     2.0             2   
522   365.00   0.000000        0.00000     NaN             6   
523   350.00  -2.000000       -0.57971    45.0            22   

     impliedVolatility  inTheMoney contractSize currency  
0             0.000000        True      REGULAR      USD  
1             0.000000        True      REGULAR      USD  
2            19.515629        True      REGULAR      USD  
3            18.804692        True      REGULAR      USD  
4             0.000000        True      REGULAR      USD  
..                 ...         ...          ...      ...  
519          10.589115       False      REGULAR      USD  
520          10.464969       False      REGULAR      USD  
521          10.253818       False      REGULAR      USD  
522          10.159489       False      REGULAR      USD  
523          10.031925       False      REGULAR      USD  

[524 rows x 14 columns]

In [17]:
callPrice = float(opt.calls.lastPrice[opt.calls.strike == 800.00])
print ('The call price is', callPrice)

The call price is 294.69


In [45]:
def newton_vol_call(S, K, T, C, r):
   
    #S: spot price
    #K: strike price
    #T: time to maturity
    #C: Call value
    #r: risk free rate
    #sigma: volatility of underlying asset

     MAX_ITERATIONS = 1000

     tolerance = 0.000001

     sigma = 0.25

     for i in range(0, MAX_ITERATIONS):

         d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))

         d2 = (np.log(S / K) + (r - 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))  

         price = S* si .norm .cdf(-d1,0.0,1.0 )-K* np .exp (-r* T)* si .norm .cdf(-d2,0.0,1.0)  

         vega= S* np .sqrt(T)* si .norm (.pdf (-d1), 0.0, 1.0)  

         diff= C-price;   if abs ((diff ))<tolerance : return sigma else :sigam= sigam+ diff/vega print("Iteration",i," "," Sigma ",round((sigam ),4),"Difference",abs ((diff )))return round((sigam ),3);


SyntaxError: invalid syntax (<ipython-input-45-eef01abdf65c>, line 24)

In [ ]:
def newton_vol_call(S, K, T, C, r):
   
    #S: spot price
    #K: strike price
    #T: time to maturity
    #C: Call value
    #r: risk free rate
    #sigma: volatility of underlying asset

     MAX_ITERATIONS = 1000

     tolerance = 0.000001

     sigma = 0.25

     for i in range(0, MAX_ITERATIONS):

         d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))

         d2 = (np.log(S / K) + (r - 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))  

         price = S* si .norm .cdf(-d1,0.0,1.0)-K* np .exp (-r* T)* si .norm .cdf(-d2,0.0,1.)  

         vega= S* np .sqrt(T)* si .norm (.pdf (-d1),0.0,1.0)  

         diff= C-price;   if abs ((diff ))<tolerance : return sigma else :sigam= sigam+ diff/vega print("Iteration",i," "," Sigma ",round((sigam ),4),"Difference",abs ((diff )))return round((sigam ),3);

In [39]:
impvol = newton_vol_call(S, 1010.00, 4/52, float(opt.calls.lastPrice[opt.calls.strike == 1010.00]), 0.0158)
print('The implied volatility is', round(impvol*100,2) , '% for the one-month call with strike $ 1010.00')

<ipython-input-5-c5fcb417c835>:16: RuntimeWarning: divide by zero encountered in log
  d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
<ipython-input-5-c5fcb417c835>:17: RuntimeWarning: divide by zero encountered in log
  d2 = (np.log(S / K) + (r - 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [25]:
import mibian

ModuleNotFoundError: No module named 'mibian'

# Binomial Tree

In [26]:
S0 = 40.0              # spot stock price
K = 40.0               # strike
T = 0.5                 # maturity 
r = 0.1                 # risk free rate 
sig = 0.1               # diffusion coefficient or volatility
N = 2                   # number of periods or number of time steps  
payoff = "call"          # payoff 

In [27]:
dT = float(T) / N                             # Delta t
u = np.exp(sig * np.sqrt(dT))                 # up factor
d = 1.0 / u                                   # down factor 

In [28]:
S = np.zeros((N + 1, N + 1))
S[0, 0] = S0
z = 1
for t in range(1, N + 1):
    for i in range(z):
        S[i, t] = S[i, t-1] * u
        S[i+1, t] = S[i, t-1] * d
    z += 1

In [29]:
S

array([[40.        , 42.05084386, 44.20683672],
       [ 0.        , 38.04917698, 40.        ],
       [ 0.        ,  0.        , 36.19349672]])

In [30]:
a = np.exp(r * dT)    # risk free compound return
p = (a - d)/ (u - d)  # risk neutral up probability
q = 1.0 - p           # risk neutral down probability
p

0.7405483598480218

In [31]:
q

0.2594516401519782

In [32]:
u

1.0512710963760241

In [33]:
d

0.9512294245007139

In [34]:
S_T = S[:,-1]
V = np.zeros((N + 1, N + 1))
if payoff =="call":
    V[:,-1] = np.maximum(S_T-K, 0.0)
elif payoff =="put":
    V[:,-1] = np.maximum(K-S_T, 0.0)
V

array([[0.        , 0.        , 4.20683672],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [35]:
# for European Option
for j in range(N-1, -1, -1):
    for i in range(j+1):
        V[i,j] = np.exp(-r*dT) * (p * V[i,j + 1] + q * V[i + 1,j + 1])
V

array([[2.19456163, 3.03844737, 4.20683672],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [36]:
print('European ' + payoff, str( V[0,0]))

European call 2.19456162714245
